Lineas comentadas

diff --git a/.github/workflows/Test-Workflow.yaml b/.github/workflows/Test-Workflow.yaml
--- a/.github/workflows/Test-Workflow.yaml
+++ b/.github/workflows/Test-Workflow.yaml
@@ -53,10 +53,10 @@ jobs:
     - name: Deploy
       run: 
           docker-compose build | docker-compose up -d
-    - name: fallo contrlado
-      id: testfallo
-      run: exit 1
+    #- name: fallo contrlado
+    #  id: testfallo
+    #  run: exit 1
 
-    - name: demo fallo
-      if: ${{ failure () && steps.testfallo.conclusion == ´failure´ }}
+   # - name: demo fallo
+   #   if: ${{ failure () && steps.testfallo.conclusion == ´failure´ }}
 
